# Generated by Django 3.2.6 on 2021-09-02 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product', '0001_initial'),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'پرداخت'), ('S', 'درحال ارسال'), ('D', 'تحویل داده شده')], default='P', max_length=1, verbose_name='وضعیت')),
                ('ordered', models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت سفارش')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='accounts.address', verbose_name='آدرس')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.codediscount', verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name_plural': 'سفارش ها',
                'ordering': ('-ordered',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book', verbose_name='کتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shoppingbasket.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name_plural': 'آیتم های سفارش',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shoppingbasket.shoppingbasket', verbose_name='سبد خرید'),
        ),
    ]
