# Generated by Django 3.2.6 on 2021-09-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True, verbose_name='اسلاگ')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('author', models.CharField(max_length=128, verbose_name='نویسنده')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('quantity', models.PositiveIntegerField(verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='عکس')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True, verbose_name='اسلاگ')),
                ('cash_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.cashdiscount', verbose_name='تخفیف نقدی')),
                ('categories', models.ManyToManyField(to='product.Category', verbose_name='دسته بندی ها')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('percentage_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.percentagediscount', verbose_name='تخفیف درصدی')),
            ],
            options={
                'verbose_name_plural': 'کتاب ها',
                'ordering': ['created'],
            },
        ),
    ]
