# Generated by Django 3.2.6 on 2021-09-02 00:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد')),
                ('started', models.DateTimeField(verbose_name='زمان شروع')),
                ('expired', models.DateTimeField(verbose_name='زمان پایان')),
                ('max_amount', models.PositiveIntegerField(verbose_name='حداکثر مقدار تخفیف (تومان)')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'تخفیف های درصدی',
            },
        ),
        migrations.CreateModel(
            name='CodeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='کد تخفیف')),
                ('percentage', models.PositiveIntegerField(verbose_name='درصد')),
                ('started', models.DateTimeField(verbose_name='زمان شروع')),
                ('expired', models.DateTimeField(verbose_name='زمان پایان')),
                ('max_amount', models.PositiveIntegerField(verbose_name='حداکثر مقدار تخفیف (تومان)')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.CreateModel(
            name='CashDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(200000)], verbose_name='مقدار (تومان)')),
                ('started', models.DateTimeField(verbose_name='زمان شروع')),
                ('expired', models.DateTimeField(verbose_name='زمان پایان')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name_plural': 'تخفیف های نقدی',
            },
        ),
    ]
